version: '3'

services:
  mysql_test:
    image: mysql:latest
    container_name: mysql_test
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=test_db
    networks:
      - my_networks

  
  phpmyadmin_test:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8181:80
    environment:
      - PMA_HOST=mysql_test
      # - PMA_ARBITRARY=1
    depends_on:
      - mysql_test
    networks:
      - my_networks



networks:
  my_networks:


